#!/usr/bin/env python3
"""Generate Thor's Python API reference pages without importing Thor."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path
import shutil
import sys
import tempfile


_OUTPUT_RELATIVE = Path("docs/reference/generated")
_STUB_RELATIVE = Path("docs/_api_stubs/thor-stubs")
_GENERATED_HEADER = "<!-- Generated by tools/docs/generate_api_reference.py; do not edit by hand. -->"


@dataclass(frozen=True)
class ModuleSurface:
    module: str
    public_names: tuple[str, ...]
    renderable_names: tuple[str, ...]
    metadata_source: str
    enumeration_complete: bool

    @property
    def pending_names(self) -> tuple[str, ...]:
        renderable = set(self.renderable_names)
        return tuple(name for name in self.public_names if name not in renderable)


def _repository_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deterministic mkdocstrings reference pages from Thor's curated Python API surface."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero instead of writing when the generated API reference is stale.",
    )
    return parser.parse_args()


def _module_name(package_root: Path, init_file: Path) -> str:
    return ".".join(init_file.parent.relative_to(package_root.parent).parts)


def _public_package_modules(package_root: Path) -> dict[str, Path]:
    modules: dict[str, Path] = {}
    for init_file in sorted(package_root.rglob("__init__.py")):
        relative_parts = init_file.parent.relative_to(package_root).parts
        if any(part.startswith("_") for part in relative_parts):
            continue
        modules[_module_name(package_root, init_file)] = init_file
    return modules


def _literal_public_names(tree: ast.Module) -> tuple[str, ...] | None:
    for statement in tree.body:
        value: ast.AST | None = None
        if isinstance(statement, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__" for target in statement.targets
        ):
            value = statement.value
        elif (
            isinstance(statement, ast.AnnAssign)
            and isinstance(statement.target, ast.Name)
            and statement.target.id == "__all__"
        ):
            value = statement.value
        if value is None:
            continue
        try:
            literal = ast.literal_eval(value)
        except (TypeError, ValueError):
            return None
        if not isinstance(literal, (list, tuple)) or not all(isinstance(item, str) for item in literal):
            return None
        return tuple(dict.fromkeys(literal))
    return None


def _stub_file(stub_root: Path, module: str) -> Path:
    parts = module.split(".")
    relative = Path(*parts[1:])
    return stub_root / relative / "__init__.pyi" if relative.parts else stub_root / "__init__.pyi"


def _stub_public_names(stub_file: Path) -> tuple[str, ...] | None:
    if not stub_file.is_file():
        return None
    tree = ast.parse(stub_file.read_text(encoding="utf-8"), filename=str(stub_file))
    explicit = _literal_public_names(tree)
    if explicit is not None:
        return explicit

    names: list[str] = []
    for statement in tree.body:
        if isinstance(statement, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if not statement.name.startswith("_"):
                names.append(statement.name)
        elif isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name):
            if not statement.target.id.startswith("_"):
                names.append(statement.target.id)
        elif isinstance(statement, ast.Assign):
            for target in statement.targets:
                if isinstance(target, ast.Name) and not target.id.startswith("_"):
                    names.append(target.id)
    return tuple(dict.fromkeys(names)) or None


def _stub_renderable_names(stub_file: Path) -> set[str] | None:
    """Return names that are materially declared by a generated stub.

    ``__all__`` describes the public namespace, but nanobind's stub generator can
    intentionally omit module metadata such as ``__version__``. Treating every
    ``__all__`` entry as renderable makes Griffe fall back to the Python-source
    alias (for example ``thor._thor.__version__``), which cannot be resolved in a
    static documentation build.
    """
    if not stub_file.is_file():
        return None

    tree = ast.parse(stub_file.read_text(encoding="utf-8"), filename=str(stub_file))
    names: set[str] = set()
    for statement in tree.body:
        if isinstance(statement, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            names.add(statement.name)
        elif isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name):
            names.add(statement.target.id)
        elif isinstance(statement, ast.Assign):
            for target in statement.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(statement, ast.ImportFrom):
            for alias in statement.names:
                if alias.name != "*":
                    names.add(alias.asname or alias.name)
        elif isinstance(statement, ast.Import):
            for alias in statement.names:
                names.add(alias.asname or alias.name.split(".")[0])
    return names


def _source_renderable_names(tree: ast.Module) -> set[str]:
    """Return names Griffe can collect from source without following thor._thor."""
    names: set[str] = set()
    for statement in tree.body:
        if isinstance(statement, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if not statement.name.startswith("_"):
                names.add(statement.name)
            continue
        if not isinstance(statement, ast.ImportFrom) or statement.level == 0:
            continue

        # Relative imports from private pure-Python helpers are fine; imports from
        # the native extension are intentionally excluded until generated stubs exist.
        source_module = statement.module or ""
        if source_module == "_thor" or source_module.startswith("_thor."):
            continue
        for alias in statement.names:
            if alias.name == "*":
                continue
            exposed = alias.asname or alias.name
            if not exposed.startswith("_"):
                names.add(exposed)
    return names


def _surface_for_module(
    module: str,
    init_file: Path,
    *,
    module_names: set[str],
    stub_root: Path,
) -> ModuleSurface:
    tree = ast.parse(init_file.read_text(encoding="utf-8"), filename=str(init_file))
    source_public = _literal_public_names(tree)
    stub_file = _stub_file(stub_root, module)
    stub_public = _stub_public_names(stub_file)
    stub_renderable = _stub_renderable_names(stub_file)

    if source_public is not None:
        public_names = source_public
        metadata_source = "python __all__"
        enumeration_complete = True
    elif stub_public is not None:
        public_names = stub_public
        metadata_source = "generated .pyi"
        enumeration_complete = True
    else:
        # No authoritative enumeration is available yet. Direct Python definitions
        # and non-native relative re-exports are still safe to expose as the subset
        # that static documentation can prove today.
        public_names = tuple(sorted(_source_renderable_names(tree)))
        metadata_source = "python static subset"
        enumeration_complete = False

    if stub_public is not None:
        # A public name is renderable from native metadata only when the stub
        # actually declares/re-exports it. ``__all__`` membership alone is not
        # sufficient for Griffe alias resolution.
        renderable = stub_renderable if stub_renderable is not None else set()
    else:
        renderable = _source_renderable_names(tree)

    renderable_names = tuple(
        name
        for name in public_names
        if name in renderable and f"{module}.{name}" not in module_names
    )
    public_names = tuple(name for name in public_names if f"{module}.{name}" not in module_names)
    return ModuleSurface(module, public_names, renderable_names, metadata_source, enumeration_complete)


def _build_surfaces(root: Path) -> list[ModuleSurface]:
    package_root = root / "bindings/python/src/thor"
    stub_root = root / _STUB_RELATIVE
    modules = _public_package_modules(package_root)
    module_names = set(modules)
    return [
        _surface_for_module(module, init_file, module_names=module_names, stub_root=stub_root)
        for module, init_file in sorted(modules.items())
    ]


def _slug(module: str) -> str:
    return module.replace(".", "-") + ".md"


def _render_index(surfaces: list[ModuleSurface]) -> str:
    lines = [
        _GENERATED_HEADER,
        "",
        "# Python API",
        "",
        "This index is generated from Thor's curated public Python package surface. "
        "The documentation build uses static analysis only and never imports `thor` or loads `_thor.so`.",
        "",
        "Native-backed namespaces automatically gain full signatures when the generated `.pyi` snapshot is available.",
        "",
    ]
    for surface in surfaces:
        pending = len(surface.pending_names)
        if not surface.enumeration_complete:
            suffix = " — native namespace awaiting stub metadata"
        elif pending:
            suffix = f" — {pending} native symbol{'s' if pending != 1 else ''} awaiting stub metadata"
        else:
            suffix = ""
        lines.append(f"- [`{surface.module}`]({_slug(surface.module)}){suffix}")
    lines.append("")
    return "\n".join(lines)


def _render_module(surface: ModuleSurface) -> str:
    lines = [
        _GENERATED_HEADER,
        "",
        f"# `{surface.module}`",
        "",
        f"Public API metadata source: **{surface.metadata_source}**.",
        "",
    ]

    if not surface.enumeration_complete:
        lines.extend(
            [
                "!!! info \"Native namespace metadata pending\"",
                "    This namespace also re-exports native-backed API whose names and signatures cannot be enumerated from Python source alone. Generated `.pyi` metadata will expand this page automatically.",
                "",
            ]
        )

    if surface.pending_names:
        count = len(surface.pending_names)
        lines.extend(
            [
                "!!! info \"Native signature metadata pending\"",
                f"    {count} public symbol{'s are' if count != 1 else ' is'} known from the Python namespace but cannot yet be rendered without generated native `.pyi` metadata. The page will expand automatically when that snapshot is present.",
                "",
            ]
        )

    if surface.renderable_names:
        for name in surface.renderable_names:
            lines.extend([f"::: {surface.module}.{name}", ""])
    else:
        lines.extend(
            [
                "No statically renderable object signatures are available for this namespace yet. "
                "Generated native stub metadata will populate this page automatically.",
                "",
            ]
        )
    return "\n".join(lines)


def _write_tree(destination: Path, surfaces: list[ModuleSurface]) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "index.md").write_text(_render_index(surfaces), encoding="utf-8")
    for surface in surfaces:
        (destination / _slug(surface.module)).write_text(_render_module(surface), encoding="utf-8")


def _files(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return sorted(path.relative_to(root) for path in root.rglob("*.md") if path.is_file())


def _trees_match(left: Path, right: Path) -> bool:
    files = _files(left)
    return files == _files(right) and all(
        (left / relative).read_bytes() == (right / relative).read_bytes() for relative in files
    )


def main() -> int:
    args = _parse_args()
    root = _repository_root()
    destination = root / _OUTPUT_RELATIVE
    surfaces = _build_surfaces(root)

    with tempfile.TemporaryDirectory(prefix="thor-api-reference-") as temporary_directory:
        staged = Path(temporary_directory) / "generated"
        _write_tree(staged, surfaces)

        if args.check:
            if _trees_match(staged, destination):
                print(f"Generated Thor API reference is current: {destination}")
                return 0
            print(
                "error: generated Thor API reference is stale; run "
                "python tools/docs/generate_api_reference.py",
                file=sys.stderr,
            )
            return 1

        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(staged, destination)

    rendered = sum(len(surface.renderable_names) for surface in surfaces)
    pending = sum(len(surface.pending_names) for surface in surfaces)
    print(
        f"Generated {len(surfaces)} namespace pages with {rendered} statically renderable public symbols "
        f"({pending} awaiting native stub metadata)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
