from collections.abc import Iterable, Sequence
import enum
from typing import TypeAlias, overload

from ._kfold import (
    make_k_fold_run_specs as make_k_fold_run_specs,
    training_runs_from_k_fold_split as training_runs_from_k_fold_split
)
import thor
import thor.data
import thor.layers
import thor.optimizers
import thor.parameters
import thor.runtime


class DatasetInputBindings:
    def __init__(self) -> None: ...

    def bind(self, network_input: thor.layers.NetworkInput, field: thor.data.DatasetField) -> DatasetInputBindings: ...

    @staticmethod
    def by_exact_name(network: thor.Network, dataset: thor.data.NamedDataset) -> DatasetInputBindings: ...

    def __len__(self) -> int: ...

    @property
    def empty(self) -> bool: ...

class DeviceDatasetStorageReport:
    @property
    def requested(self) -> thor.data.DeviceDatasetStorage: ...

    @property
    def attempted(self) -> bool: ...

    @property
    def used(self) -> bool: ...

    @property
    def reason(self) -> str: ...

    @property
    def examples(self) -> int: ...

    @property
    def required_bytes(self) -> int: ...

    @property
    def available_bytes_after_model_placement(self) -> int: ...

    @property
    def resident_bytes(self) -> int: ...

    @property
    def resident_cache_hit(self) -> bool: ...

    @property
    def resident_construction_joined(self) -> bool: ...

    @property
    def resident_construction_started(self) -> bool: ...

    @property
    def materialization_seconds(self) -> float: ...

EarlyCompletionPolicy: TypeAlias = TrainingEarlyCompletionPolicy

EarlyCompletionRule: TypeAlias = TrainingRunsEarlyCompletionRule

class GradientClearPolicy(enum.Enum):
    clear_before_step = 0

    accumulate = 1

RestartCondition: TypeAlias = TrainingRestartPolicy

RestartPolicy: TypeAlias = TrainingRestartPolicy

class StepExecutable:
    def is_initialized(self) -> bool: ...

    @property
    def name(self) -> str: ...

    @property
    def repeat_count(self) -> int: ...

    @property
    def gradient_clear_policy(self) -> GradientClearPolicy: ...

    def get_active_phase_names(self) -> list[str]: ...

    def get_optimizer(self) -> thor.optimizers.Optimizer: ...

    def get_update_parameter_references(self) -> list[thor.parameters.ParameterReference]: ...

    def get_resolved_update_parameters(self) -> list[thor.parameters.BoundParameter]: ...

    def get_input_bindings(self) -> list[TrainingInputBinding]: ...

    def get_resolved_input_bindings(self) -> list[TrainingInputBinding]: ...

    def get_required_batch_input_names(self) -> list[str]: ...

    def get_architecture_json(self) -> str: ...

class Trainer:
    def __init__(self, network: thor.Network | None = None, optimizer: thor.optimizers.Optimizer | None = None, training_program: object | None = None, debug_synchronous: bool = False, stats_interval_s: float = 10.0, max_in_flight_batches: int = 32, scalar_tensors_to_report: Sequence[str] = ['loss'], stats_stderr_also: bool = False, stats_color: str = 'auto', save_model_dir: object | None = None, save_model_overwrite: bool = False, model_selection_score: object | None = None, data: thor.data.TrainingData | None = None, input_bindings: DatasetInputBindings | None = None) -> None: ...

    def fit(self, epochs: int, check_best_model_every_epochs: int = 0, first_model_selection_epoch: int = 0, restart_conditions: object | None = None, early_completion_policies: object | None = None, max_training_batches_per_epoch: object | None = None) -> object: ...

    def save_model(self, directory: object, overwrite: bool = False, save_optimizer_state: bool = True) -> None: ...

    @property
    def completed_training_epochs(self) -> int: ...

    @property
    def completed_training_elapsed_seconds(self) -> float: ...

class TrainerFitOptions:
    def __init__(self) -> None: ...

    @property
    def epochs(self) -> int: ...

    @epochs.setter
    def epochs(self, arg: int, /) -> None: ...

    @property
    def check_best_model_every_epochs(self) -> int: ...

    @check_best_model_every_epochs.setter
    def check_best_model_every_epochs(self, arg: int, /) -> None: ...

    @property
    def first_model_selection_epoch(self) -> int: ...

    @first_model_selection_epoch.setter
    def first_model_selection_epoch(self, arg: int, /) -> None: ...

    @property
    def max_training_batches_per_epoch(self) -> int | None: ...

    @max_training_batches_per_epoch.setter
    def max_training_batches_per_epoch(self, arg: int) -> None: ...

class TrainingEarlyCompletionPolicy:
    pass

class TrainingEnsembleMemberResult:
    @property
    def run_name(self) -> str: ...

    @property
    def weight(self) -> float: ...

    @property
    def status(self) -> str: ...

    @property
    def status_enum(self) -> TrainingRunStatus: ...

    @property
    def final_training_loss(self) -> object: ...

    @property
    def final_validation_loss(self) -> object: ...

    @property
    def final_test_loss(self) -> object: ...

    @property
    def final_test_metrics(self) -> dict[str, float]: ...

class TrainingEnsembleResult:
    @property
    def ensemble_group(self) -> str: ...

    @property
    def members(self) -> list[TrainingEnsembleMemberResult]: ...

    @property
    def input_signature(self) -> list[TrainingRunInputSignature]: ...

    @property
    def output_signature(self) -> list[TrainingRunOutputSignature]: ...

    def __len__(self) -> int: ...

    def __bool__(self) -> bool: ...

    def all_completed(self) -> bool: ...

    def any_failed(self) -> bool: ...

    def has_enough_successful_models(self) -> bool: ...

    @property
    def successful_models(self) -> int: ...

    @property
    def required_successful_models(self) -> int: ...

    @property
    def min_successful_models(self) -> int: ...

    @property
    def target_num_members(self) -> int: ...

    @property
    def actual_num_members(self) -> int: ...

    @property
    def total_weight(self) -> float: ...

    @property
    def status_counts(self) -> dict[str, int]: ...

    @property
    def named_metrics(self) -> list[TrainingNamedMetricResult]: ...

    @property
    def graph_metrics(self) -> list[TrainingNamedMetricResult]: ...

    @property
    def reported_metrics(self) -> list[TrainingNamedMetricResult]: ...

    def has_named_metric_values(self) -> bool: ...

    def has_graph_metric_values(self) -> bool: ...

    def has_ensemble_evaluation_metrics(self) -> bool: ...

    @property
    def ensemble_training_loss(self) -> object: ...

    @property
    def ensemble_train_loss(self) -> object: ...

    @property
    def ensemble_test_loss(self) -> object: ...

class TrainingEventPhase(enum.Enum):
    unknown = 0

    train = 1

    validate = 2

    test = 3

class TrainingInputBinding:
    def __init__(self, network_input_name: str, batch_input_name: str) -> None: ...

    @property
    def network_input_name(self) -> str: ...

    @property
    def batch_input_name(self) -> str: ...

    def is_initialized(self) -> bool: ...

    def get_architecture_json(self) -> str: ...

    @staticmethod
    def deserialize(architecture_json: str) -> TrainingInputBinding: ...

    def __eq__(self, arg: TrainingInputBinding, /) -> bool: ...

class TrainingNamedMetricResult:
    @property
    def name(self) -> str: ...

    @property
    def train_value(self) -> object: ...

    @property
    def test_value(self) -> object: ...

    def has_value(self) -> bool: ...

class TrainingPhase:
    def __init__(self, name: str, network: thor.Network, enabled: bool = True) -> None: ...

    @property
    def name(self) -> str: ...

    @property
    def enabled(self) -> bool: ...

    @enabled.setter
    def enabled(self, arg: bool, /) -> None: ...

    def is_initialized(self) -> bool: ...

    def is_enabled(self) -> bool: ...

    def enable(self) -> None: ...

    def disable(self) -> None: ...

    def set_enabled(self, enabled: bool) -> None: ...

    def get_network(self) -> thor.Network: ...

    def get_outputs(self) -> dict[str, thor.Tensor]: ...

    def get_architecture_json(self) -> str: ...

    @staticmethod
    def deserialize(architecture_json: str) -> TrainingPhase: ...

class TrainingProgram:
    def __init__(self, steps: object | None = None) -> None: ...

    def add_step(self, step: TrainingStep) -> None: ...

    def get_num_steps(self) -> int: ...

    def get_step(self, index: int) -> TrainingStep: ...

    def get_steps(self) -> list[TrainingStep]: ...

    def is_initialized(self) -> bool: ...

    def get_architecture_json(self) -> str: ...

    @staticmethod
    def deserialize(architecture_json: str) -> TrainingProgram: ...

    def compile(self, placed_network: thor.runtime.PlacedNetwork, resolve_empty_update_parameters_as_all_trainable: bool = True) -> list[StepExecutable]: ...

TrainingRestartCondition: TypeAlias = TrainingRestartPolicy

class TrainingRestartPolicy:
    def __init__(self, run_name: str | None = None, ensemble_group: str | None = None, progress_check_epochs: int = 3, progress_improvement_min_percentage: float = 5.0, max_restarts: int = 5) -> None: ...

    @property
    def run_name(self) -> object: ...

    @property
    def ensemble_group(self) -> object: ...

    @property
    def progress_check_epochs(self) -> int: ...

    @property
    def progress_improvement_min_percentage(self) -> float: ...

    @property
    def max_restarts(self) -> int: ...

class TrainingRunCompletionReason(enum.Enum):
    completed = 0

    early_completed = 1

class TrainingRunInputSignature:
    @property
    def input_name(self) -> str: ...

    @property
    def dimensions(self) -> list[int]: ...

    @property
    def data_type(self) -> str: ...

    @property
    def dimensions_include_batch(self) -> bool: ...

class TrainingRunOutputSignature:
    @property
    def output_name(self) -> str: ...

    @property
    def dimensions(self) -> list[int]: ...

    @property
    def data_type(self) -> str: ...

class TrainingRunResult:
    @property
    def run_name(self) -> str: ...

    @property
    def ensemble_group(self) -> object: ...

    @property
    def ensemble_weight(self) -> float: ...

    @property
    def status(self) -> str: ...

    @property
    def status_enum(self) -> TrainingRunStatus: ...

    @property
    def result(self) -> str: ...

    @property
    def completion_reason(self) -> str: ...

    @property
    def completion_reason_enum(self) -> TrainingRunCompletionReason: ...

    @property
    def early_completed(self) -> bool: ...

    @property
    def completed_epoch(self) -> object: ...

    @property
    def selected_epoch(self) -> object: ...

    @property
    def best_epoch(self) -> object: ...

    @property
    def best_score(self) -> object: ...

    @property
    def latest_score(self) -> object: ...

    @property
    def selected_score(self) -> object: ...

    @property
    def best_model_selection(self) -> object: ...

    @property
    def saved_model_dir(self) -> object: ...

    @property
    def saved_model_network_name(self) -> object: ...

    @property
    def exception_type(self) -> str: ...

    @property
    def exception_message(self) -> str: ...

    @property
    def final_training_stats(self) -> TrainingStatsSnapshot | None: ...

    @property
    def final_validation_stats(self) -> TrainingStatsSnapshot | None: ...

    @property
    def final_validation_stats_by_population(self) -> dict: ...

    @property
    def final_test_stats(self) -> TrainingStatsSnapshot | None: ...

    @property
    def final_training_loss(self) -> object: ...

    @property
    def final_validation_loss(self) -> object: ...

    @property
    def final_test_loss(self) -> object: ...

    def final_loss(self, phase: str) -> object: ...

    @property
    def final_training_step(self) -> object: ...

    @property
    def final_validation_step(self) -> object: ...

    @property
    def final_test_step(self) -> object: ...

    def completed(self) -> bool: ...

    def failed(self) -> bool: ...

    def cancelled(self) -> bool: ...

class TrainingRuns:
    def __init__(self, runs: Iterable, failure_policy: str = 'cancel_siblings', max_summary_logs_per_second: float = 2.0, max_parallel_runs: int | None = 3, min_successful_models: object | None = None) -> None: ...

    @property
    def max_parallel_runs(self) -> object: ...

    @property
    def effective_max_parallel_runs(self) -> int: ...

    @property
    def reports(self) -> dict[str, list[str]]: ...

    def fit(self, epochs: int, test_data: thor.data.TrainingData | None = None, check_best_model_every_epochs: int = 0, first_model_selection_epoch: int = 0, restart_conditions: object | None = None, early_completion_rules: object | None = None, reports: object | None = None, evaluate_training_population: bool = True, max_training_batches_per_epoch: object | None = None) -> TrainingRunsResult: ...

TrainingRunsEarlyCompletionPolicy: TypeAlias = TrainingRunsEarlyCompletionRule

class TrainingRunsEarlyCompletionRule(TrainingEarlyCompletionPolicy):
    @property
    def run_name(self) -> object: ...

    @property
    def ensemble_group(self) -> object: ...

class TrainingRunsFailurePolicy(enum.Enum):
    cancel_siblings = 1

TrainingRunsRestartCondition: TypeAlias = TrainingRestartPolicy

TrainingRunsRestartPolicy: TypeAlias = TrainingRestartPolicy

class TrainingRunsResult:
    def __len__(self) -> int: ...

    def __bool__(self) -> bool: ...

    @overload
    def __getitem__(self, arg: int, /) -> TrainingRunResult: ...

    @overload
    def __getitem__(self, arg: str, /) -> TrainingRunResult: ...

    @property
    def runs(self) -> list[TrainingRunResult]: ...

    @property
    def ensembles(self) -> list[TrainingEnsembleResult]: ...

    @property
    def has_ensembles(self) -> bool: ...

    def ensemble(self, ensemble_group: str) -> TrainingEnsembleResult: ...

    def all_completed(self) -> bool: ...

    def any_failed(self) -> bool: ...

    def any_cancelled(self) -> bool: ...

    @property
    def status_counts(self) -> dict[str, int]: ...

    def get_status_counts(self) -> dict[str, int]: ...

    def save_ensemble(self, ensemble_group: str, path: object, aggregation: str = 'auto', overwrite: bool = False) -> str: ...

class TrainingRunStatus(enum.Enum):
    not_started = 0

    starting = 7

    waiting_to_start = 8

    waiting_for_memory = 9

    running = 1

    completed = 2

    failed = 3

    cancelled = 4

    interrupted = 5

    oom = 6

class TrainingStatsSnapshot:
    @property
    def network_name(self) -> str: ...

    @property
    def dataset_name(self) -> str: ...

    @property
    def phase(self) -> TrainingEventPhase: ...

    @property
    def validation_population(self) -> str: ...

    @property
    def is_default_validation_population(self) -> bool: ...

    @property
    def epoch(self) -> int: ...

    @property
    def epochs(self) -> int: ...

    @property
    def step(self) -> int: ...

    @property
    def step_in_epoch(self) -> int: ...

    @property
    def steps_per_epoch(self) -> int: ...

    @property
    def batch_size(self) -> int: ...

    @property
    def valid_examples_in_batch(self) -> int: ...

    @property
    def samples_processed_in_epoch(self) -> int: ...

    @property
    def samples_processed(self) -> int: ...

    @property
    def in_flight_batches(self) -> int: ...

    @property
    def elapsed_seconds(self) -> float: ...

    @property
    def samples_per_second(self) -> float: ...

    @property
    def batches_per_second(self) -> float: ...

    @property
    def floating_point_operations_per_batch(self) -> int: ...

    @property
    def floating_point_operations_per_second(self) -> float: ...

    @property
    def loss(self) -> object: ...

    @property
    def accuracy(self) -> object: ...

    @property
    def learning_rate(self) -> object: ...

    @property
    def momentum(self) -> object: ...

    @property
    def losses(self) -> dict[str, float]: ...

    @property
    def metrics(self) -> dict[str, float]: ...

    @property
    def device_dataset_storage(self) -> DeviceDatasetStorageReport: ...

class TrainingStep:
    def __init__(self, name: str, phases: Sequence[TrainingPhase], optimizer: thor.optimizers.Optimizer | None = None, update_parameters: Sequence[thor.parameters.ParameterReference] = [], repeat_count: int = 1, gradient_clear_policy: GradientClearPolicy = GradientClearPolicy.clear_before_step, input_bindings: Sequence[TrainingInputBinding] = [], enabled: bool = True) -> None: ...

    @property
    def name(self) -> str: ...

    @property
    def repeat_count(self) -> int: ...

    @property
    def gradient_clear_policy(self) -> GradientClearPolicy: ...

    @property
    def enabled(self) -> bool: ...

    @enabled.setter
    def enabled(self, arg: bool, /) -> None: ...

    def is_initialized(self) -> bool: ...

    def is_enabled(self) -> bool: ...

    def enable(self) -> None: ...

    def disable(self) -> None: ...

    def set_enabled(self, enabled: bool) -> None: ...

    def get_active_phase_names(self) -> list[str]: ...

    def get_phases(self) -> list[TrainingPhase]: ...

    def get_optimizer(self) -> thor.optimizers.Optimizer: ...

    def get_update_parameters(self) -> list[thor.parameters.ParameterReference]: ...

    def get_input_bindings(self) -> list[TrainingInputBinding]: ...

    def updates_parameter(self, parameter: thor.parameters.ParameterReference) -> bool: ...

    def get_architecture_json(self) -> str: ...

    @staticmethod
    def deserialize(architecture_json: str) -> TrainingStep: ...

__all__: list = ['DatasetInputBindings', 'DeviceDatasetStorageReport', 'EarlyCompletionPolicy', 'EarlyCompletionRule', 'GradientClearPolicy', 'RestartCondition', 'RestartPolicy', 'StepExecutable', 'Trainer', 'TrainerFitOptions', 'TrainingEarlyCompletionPolicy', 'TrainingEnsembleMemberResult', 'TrainingEnsembleResult', 'TrainingEventPhase', 'TrainingInputBinding', 'TrainingNamedMetricResult', 'TrainingPhase', 'TrainingProgram', 'TrainingRestartCondition', 'TrainingRestartPolicy', 'TrainingRunCompletionReason', 'TrainingRunInputSignature', 'TrainingRunOutputSignature', 'TrainingRunResult', 'TrainingRuns', 'TrainingRunsEarlyCompletionPolicy', 'TrainingRunsEarlyCompletionRule', 'TrainingRunsFailurePolicy', 'TrainingRunsRestartCondition', 'TrainingRunsRestartPolicy', 'TrainingRunsResult', 'TrainingRunStatus', 'TrainingStatsSnapshot', 'TrainingStep', 'make_k_fold_run_specs', 'training_runs_from_k_fold_split']

def __dir__() -> list[str]: ...
