#pragma once

// Hot-path timing diagnostics are compiled out by default.  Defining
// THOR_ENABLE_TRAINING_QUEUE_DIAGNOSTICS=1 at compile time re-enables the
// existing environment-variable controlled queue/batch timing diagnostics.
#ifndef THOR_ENABLE_TRAINING_QUEUE_DIAGNOSTICS
#define THOR_ENABLE_TRAINING_QUEUE_DIAGNOSTICS 0
#endif

#ifndef THOR_ENABLE_BATCH_SUBMISSION_TIMING
#define THOR_ENABLE_BATCH_SUBMISSION_TIMING THOR_ENABLE_TRAINING_QUEUE_DIAGNOSTICS
#endif

#ifndef THOR_ENABLE_BATCH_ASSEMBLER_DIAGNOSTICS
#define THOR_ENABLE_BATCH_ASSEMBLER_DIAGNOSTICS THOR_ENABLE_TRAINING_QUEUE_DIAGNOSTICS
#endif

#ifndef THOR_ENABLE_LAYER_SUBMIT_DIAGNOSTICS
#define THOR_ENABLE_LAYER_SUBMIT_DIAGNOSTICS THOR_ENABLE_TRAINING_QUEUE_DIAGNOSTICS
#endif

#ifndef THOR_ENABLE_TRAINING_UPDATE_DIAGNOSTICS
#define THOR_ENABLE_TRAINING_UPDATE_DIAGNOSTICS 0
#endif
